
    tags:
      - Questions
    parameters:
     - in: body
       name: Comment
       schema:
        id: comment_data
        properties:
            question:
              type: integer
              description: The id of the questin 
            comment:
              type: string
              description: The comment message
    responses:
      406:
        description: On failure to pass the validations
        schema:
          id: invalid_data
          properties:
             error:
              type: string
              description: The error message
             status:
              type: integer
              default: 406
              description: the status code returned
      401:
        description: error when token has expired
        schema:
          id: expired token
          properties:
             error:
              type: string
              description: The error message
             status:
              type: integer
              default: 401
              description: the status code returned
      201:
        description: Successful post of question
        schema:
          id: comment
        description: successful signup
        schema:
          id: signup
          properties:
            data:
              type: array
              items:
                type: object
                properties:
                  body:
                    type: string
                    description: The body of the question
                  comment:
                    type: string
                    description: The messagge in the comment
                  title:
                    type: string
                    description: The title of the question
                  question:
                    type: integer
                    description: The id of the question
            status:
              type: integer
              description: The status code
              default: 201