    tags:
      - Questions
    parameters:
     - in: body
       name: post-question
       schema:
        id: question_data
        properties:
            title:
              type: string
              description: The title of the question 
            createdBy:
              type: string
              description: The creator of the question
            body:
              type: string
              description: The body fo the question being asked
            meetup:
              type: integer
              description: The id of the meetup against which the question is posted
    responses:
      406:
        description: On failure to pass the validations
        schema:
          id: invalid_data
          properties:
             error:
              type: string
              description: The error message
             status:
              type: integer
              default: 406
              description: the status code returned
      401:
        description: error when token has expired and when the question has been asked before
        schema:
          id: expired token
          properties:
             error:
              type: string
              description: The error message
             status:
              type: integer
              default: 401
              description: the status code returned
      201:
        description: Successful post of question
        schema:
          id: post-question-result
          properties:
            data:
              type: array
              items:
                type: object
                properties:
                  body:
                    type: string
                    description: The body of the question
                  createdBy:
                    type: integer
                    description: The id of the author of question"
                  title:
                    type: string
                    description: The title of the question
                  question:
                    id: integer
                    description: The id of the question
                  votes:
                    type: integer
                    description: The number of votes against a question
                  meetup:
                    type: integer
                    description: The id of the meetup
                  createdOn:
                    type: string
                    description: The date of creation of the question
                  message:
                    type: string
                    description: The success message after successful creation of question
            status:
              type: integer
              description: The status code
              default: 201
      422:
        description: Error on post of non json object
        schema:
          id: non_json_data
          properties:
             error:
              type: string
              description: The error message
             status:
              type: integer
              default: 422
              description: the status code returned
