    tags:
      - meetups
    responses:
      404:
        description: Successful retrieval of meetup
        schema:
          id: specific_meetup_data
          properties:
            error:
              type: string
              description: The Error message when a meetup with a given id does not exist
            status:
              type: integer
              description: The status code
              default: 404
      200:
        description: Successful retrieval of meetup
        schema:
          id: specific_meetup_data
          properties:
            data:
              type: array
              items:
                type: object
                properties:
                  createdOn:
                    type: string
                    description: The date the meetup is created
                  happeningOn:
                    type: string
                    description: The date the meetup is to happen
                  id:
                    type: integer
                    description: The id of the meetup
                  location:
                    type: string
                    description: The location of the meetup
                  tags:
                    type: string
                    description: The tags of the meetup
                  topic:
                    type: string
                    description: The topic of the meetup
            message:
              type: string
              description: The message on successful retrieval of meetup
            status:
              type: integer
              description: The status code
              default: 200