    tags:
      - Users
    parameters:
     - in: body
       name: user
       schema:
        id: userdata
        properties:
            firstname:
              type: string
              description: The user's first name 
            lastname:
              type: string
              description: The user's last name
            othername:
              type: string
              description: The other name of the user
            phoneNumber:
              type: string
              description: The phone nnumber of the user
            username:
              type: string
              description: The username of the given user
            isAdmin:
              type: string
              default: "False"
              description: The role of the admin
            email:
              type: string
              description: The email address of the user
            password: 
              type: string
              description: The password of the user
    responses:
      406:
        description: Error on failure to pass the validations
        schema:
          id: invalid_data
          properties:
             error:
              type: string
              description: The error message
             status:
              type: integer
              default: 406
              description: the status code returned
      422:
        description: Error on post of non json object
        schema:
          id: non_json_data
          properties:
             error:
              type: string
              description: The error message
             status:
              type: integer
              default: 422
              description: the status code returned

      201:
        description: successful signup
        schema:
          id: signup
          properties:
            data:
              type: array
              items:
                type: object
                properties:
                  email:
                    type: string
                    description: The email address of the user
                  firstname:
                    type: string
                    description: The first name of the user
                  id:
                    type: integer
                    description: The autogenerated user id
                  isAdmin:
                    type: string
                    description: The role of the user
                  lastname:
                    type: string
                    description: The last name of the user
                  othername:
                    type: string
                    description: The other name of the user
                  phoneNumber:
                    type: string
                    description: The phone number of the user
                  registered:
                    type: string
                    description: The date when the user was registered
            status:
              type: integer
              default: 201
              description: The status code on successful signup
            message:
              type: string
              default: Successfully signed up
              description: An informative message on successful signup
