
    tags:
      - Questions
    responses:
      201:
        description: Successful patch on the question
        schema:
          id: voting
          properties:
            data:
              type: object
              properties:
                body:
                  type: string
                  description: The body of the question
                createdBy:
                  type: string
                  description: The id of the voter
                title:
                  type: string
                  description: "The title of the question"
                question:
                  type: integer
                  description: "The id of the question"
                status:
                   type: integer
                   description: The status code
                   default: 201
                votes:
                  type: integer
                  description: The number of votes agains the question
                message:
                  type: string
                  description: the message on successful vote
            comment:
              type: string
              description: The comment message